### ISSUE TITLE
implement decoder service with Beam

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#35]
https://github.com/mozilla/gcp-ingestion/blob/master/docs/decoder.md

steps in decoder:

- [x] #46 parse `uri`
- [x] #41 decode body gzip
- [x] #52 validate schema https://github.com/everit-org/json-schema
- [x] #37 resolve geoip https://github.com/maxmind/GeoIP2-java
- [x] #43 parse `user_agent`
- [x] #58 add `attributeMap` to message as `metadata`

deduplication is in issue #59
